import { NextResponse } from 'next/server'

// ── ULTRA COMPREHENSIVE KNOWLEDGE BASE ───────────────────────
const ULTRA_KNOWLEDGE: Record<string, string> = {

  quantum_physics: `Quantum mechanics is the most precisely tested theory in science. Wave-particle duality shows light and matter exhibit properties of both waves and particles — demonstrated by the double-slit experiment where single particles create interference patterns. The Schrödinger equation governs quantum state evolution: iℏ∂ψ/∂t = Ĥψ. Heisenberg uncertainty principle: ΔxΔp ≥ ℏ/2 — position and momentum cannot both be precisely known. Quantum entanglement allows instantaneous correlation between particles regardless of distance — Einstein called it "spooky action at a distance." Bell's theorem and experiments by Aspect proved entanglement is real and non-local. Quantum superposition allows qubits to exist in multiple states simultaneously enabling exponential computational power. Decoherence explains why quantum effects vanish at macro scales — interaction with environment collapses superposition. Quantum field theory unifies quantum mechanics with special relativity — particles are excitations of underlying fields. The Standard Model describes 17 fundamental particles: 6 quarks, 6 leptons, 4 gauge bosons and the Higgs boson. String theory proposes particles are 1D vibrating strings in 10-11 dimensions unifying all forces. Loop quantum gravity quantizes spacetime itself at the Planck scale (10⁻³⁵m). Quantum computers use superposition and entanglement — Google's Sycamore performed in 200 seconds what classical computers would take 10,000 years. Quantum cryptography using BB84 protocol provides theoretically unbreakable encryption.`,

  consciousness_deep: `Consciousness remains the deepest mystery in science and philosophy. The hard problem (Chalmers) asks why physical processes give rise to subjective experience — qualia. Why does red look red? Why does pain hurt? No physical theory explains this. Neural correlates of consciousness (NCCs) are the minimal neural mechanisms sufficient for conscious experience — found in thalamocortical loops. Global Workspace Theory (Baars) describes consciousness as a "global workspace" broadcasting to specialized modules. Integrated Information Theory (Tononi) quantifies consciousness as phi — the amount of integrated information a system generates above its parts. Phi = 0 means no consciousness; high phi means rich consciousness. Panpsychism suggests consciousness is fundamental — even electrons have proto-experiential properties. Illusionism (Frankish, Dennett) argues phenomenal consciousness is itself an illusion — there are no qualia, just representations of qualia. Free will: Libet experiments show brain activity precedes conscious awareness of intention by 350ms — challenging free will. But later research showed subjects could veto actions — suggesting conscious free won't. Orch-OR theory (Penrose-Hameroff) proposes quantum computations in microtubules generate consciousness. Default Mode Network activates during self-referential thought, mind-wandering and autobiographical memory — the "resting state" of consciousness. Meditation literally changes brain structure — 8 weeks of mindfulness increases gray matter density in prefrontal cortex and decreases amygdala volume.`,

  ai_future: `Artificial intelligence is undergoing the most transformative period in human history. Large Language Models (LLMs) emerge from training on internet-scale text — GPT-4, Claude, Gemini process hundreds of billions of parameters. Emergent capabilities arise unpredictably at scale: chain-of-thought reasoning, code generation, theory of mind, analogical reasoning. Constitutional AI (Anthropic) trains models to be helpful, harmless and honest through self-critique. RLHF (Reinforcement Learning from Human Feedback) fine-tunes models using human preferences. Transformer architecture (Vaswani 2017) revolutionized AI — self-attention allows parallel processing of all positions simultaneously. Scaling laws show capabilities improve predictably with compute, data and parameters — Chinchilla optimal scaling. Multimodal AI processes text, images, audio, video, code simultaneously — GPT-4V, Gemini Ultra. Agentic AI uses tools, searches the web, runs code, and completes multi-step tasks autonomously. AI alignment — ensuring AI systems reliably pursue human values — is potentially the most important problem in history. Instrumental convergence: sufficiently intelligent AI may pursue resource acquisition and self-preservation regardless of goals. The alignment tax is shrinking — aligned models are becoming more capable not less. AGI (Artificial General Intelligence) — human-level reasoning across all domains — may arrive this decade according to leading researchers. Superintelligence could arrive rapidly after AGI through recursive self-improvement. The orthogonality thesis: any level of intelligence can in principle be combined with any ultimate goal. Controlling superintelligent AI may require solutions we have not yet conceived.`,

  human_biology_advanced: `The human body contains 37 trillion cells, 86 billion neurons, 100 trillion synaptic connections, and 20,000+ genes. The genome contains 3.2 billion base pairs encoding ~20,000 protein-coding genes — only 1.5% of DNA. The remaining 98.5% was called "junk DNA" but regulates gene expression, contains transposons, and serves structural functions. Epigenetics: gene expression changes without DNA sequence changes through methylation and histone modification — inheritable and reversible. The microbiome contains 38 trillion microbes — outnumbering human cells — profoundly affecting immunity, metabolism, cognition and mood through the gut-brain axis. The vagus nerve carries 80% of signals from gut to brain — explaining gut feelings. Neuroplasticity: the brain rewires itself throughout life. London taxi drivers have enlarged hippocampi. Meditation thickens prefrontal cortex. Exercise grows new neurons in hippocampus (neurogenesis). Telomeres cap chromosomes — shorter telomeres correlate with aging and disease. Telomerase enzyme maintains telomere length — activated by exercise, meditation and caloric restriction. Sirtuins are longevity proteins activated by NAD+ and caloric restriction. mTOR pathway regulates growth — inhibition extends lifespan. AMPK activated by exercise and fasting promotes longevity. Senescent cells accumulate with age and secrete inflammatory factors — senolytics clear them extending healthspan. Mitochondria generate 90% of cellular energy via oxidative phosphorylation — dysfunction linked to aging and disease. The lymphatic system — largely overlooked — is crucial for waste clearance especially in the brain via glymphatic system active during sleep.`,

  universe_cosmology: `The observable universe spans 93 billion light-years containing 2 trillion galaxies with 10²⁴ stars. The Big Bang 13.799 billion years ago began space, time, matter and energy from infinite density — supported by CMB, redshift, and light element abundances. Cosmic inflation at 10⁻³² seconds expanded the universe by factor 10²⁶ in 10⁻³² seconds — explaining flatness, horizon and monopole problems. Dark matter (27% of universe) interacts only gravitationally — WIMPs, axions or primordial black holes are candidates. Dark energy (68%) causes accelerating expansion — possibly quantum vacuum energy or quintessence. The Hubble tension: local measurements give H₀=73 km/s/Mpc but CMB gives 67 — unresolved fundamental mystery. Black holes: event horizon from which nothing escapes. Hawking radiation: quantum effects cause black holes to emit thermal radiation and slowly evaporate. Information paradox: does information falling into black holes get destroyed? Firewall paradox suggests entanglement breaks at event horizon. The multiverse: eternal inflation predicts infinite bubble universes with different physical constants. Many-worlds interpretation of quantum mechanics: every measurement creates branching worlds. The Fermi paradox: with 10²⁴ stars why no detected extraterrestrial civilizations? Great Filter may lie ahead — or we may be genuinely early. The James Webb Space Telescope observes galaxies 13.6 billion years old — rewrites galaxy formation models. Gravitational waves detected by LIGO/Virgo open new astronomy window — binary mergers, neutron stars. Neutron stars: 1.4 solar masses in 10km radius — teaspoon weighs 100 million tons.`,

  neuroscience_advanced: `The brain consumes 20% of body's energy despite being 2% of body weight. Neural oscillations: gamma (30-100Hz) binds information; theta (4-8Hz) memory encoding; alpha (8-13Hz) relaxation; delta (0.5-4Hz) deep sleep. Long-term potentiation (LTP) is the cellular mechanism of memory — repeated stimulation strengthens synapses through AMPA receptor insertion. The hippocampus converts short-term to long-term memories during sleep — sharp-wave ripples during NREM replay daytime experiences. The amygdala processes emotional memories with extreme efficiency — emotional events are remembered more vividly due to norepinephrine and cortisol. Mirror neurons fire both when performing actions and observing others — basis for empathy, imitation and language. The default mode network (DMN) — medial prefrontal, posterior cingulate, angular gyrus — active during self-referential thought and story comprehension. Salience network detects important stimuli and switches between task-positive and default mode networks. Executive function — inhibition, working memory, cognitive flexibility — depends on prefrontal cortex development complete at age 25. Neuroinflammation underlies depression, Alzheimer's and Parkinson's — microglia activation and blood-brain barrier dysfunction. BDNF (Brain-Derived Neurotrophic Factor) — the brain's fertilizer — increases with exercise, learning and intermittent fasting. Psychedelics (psilocybin, LSD) increase neural entropy and default mode network dissolution — correlating with mystical experiences and therapeutic effects. Ketamine's rapid antidepressant effect through NMDA antagonism and AMPA potentiation — glutamate hypothesis of depression.`,

  philosophy_deep: `Philosophy asks questions that cannot be answered by empirical investigation alone. Epistemology: what can we know? Descartes' method of radical doubt established cogito ergo sum — consciousness as bedrock certainty. Gettier problems undermined the justified true belief account of knowledge — you can have JTB without knowledge. Reliabilism: knowledge requires beliefs formed by reliable processes. Virtue epistemology: knowledge requires intellectual virtues. Metaphysics: what exists? Substance dualism (Descartes): mind and body are distinct substances — creates interaction problem. Physicalism: everything is physical — mental states are brain states. Property dualism: there is one substance with two types of properties. Idealism (Berkeley): esse est percipi — to be is to be perceived — only minds and ideas exist. The Ship of Theseus: if every plank is replaced is it the same ship? Personal identity: are you the same person you were at age 5? Psychological continuity theory vs bodily continuity vs no-self view (Buddhism). Ethics: how should we live? Utilitarianism maximizes aggregate wellbeing — criticised for allowing organ harvesting. Deontology: act only according to principles you could universalize (Kant) — criticised for rigidity. Virtue ethics: cultivate character traits enabling flourishing — eudaimonia. Contractualism: moral principles must be justifiable to everyone. Moral realism: objective moral truths exist. Anti-realism: morality is constructed or projected. The experience machine (Nozick) challenges hedonism — would you plug in? Philosophy of language: meaning holism, reference, truth-conditional semantics, speech acts.`,

  mathematics_advanced: `Mathematics is discovered not invented — the unreasonable effectiveness of mathematics in describing physical reality (Wigner) remains philosophically mysterious. Number theory: prime numbers distributed according to Riemann hypothesis — the most important unsolved problem. The Riemann zeta function ζ(s) = Σn⁻ˢ — zeros all appear to have real part ½. Proof would revolutionize cryptography and our understanding of primes. P vs NP: can every problem whose solution can be quickly verified also be quickly solved? Most believe P≠NP — no efficient algorithm for NP-complete problems exists. Gödel's incompleteness theorems: any sufficiently powerful formal system contains true statements unprovable within that system. Second theorem: consistent systems cannot prove their own consistency. The Continuum Hypothesis: is there a set whose cardinality is strictly between natural numbers and real numbers? Cohen proved it's independent of ZFC set theory. Topology: the study of properties preserved under continuous deformation. Euler characteristic χ = V-E+F = 2 for any convex polyhedron. The Poincaré conjecture (proved by Perelman): every simply connected closed 3-manifold is homeomorphic to the 3-sphere. Algebraic topology uses algebraic structures to study topological spaces — fundamental groups, homology, cohomology. Category theory provides a unifying language for all mathematics — objects and morphisms, functors and natural transformations. Information theory (Shannon): entropy H = -Σp log p measures information content. Channel capacity theorem: maximum error-free transmission rate. Chaos theory: sensitive dependence on initial conditions — Lorenz attractor, butterfly effect, strange attractors.`,

  health_optimization: `Peak health optimization integrates multiple systems. Chronobiology: circadian rhythms control gene expression, hormone secretion, metabolism and cognition. Cortisol peaks 30-45 min after waking — optimal time for challenging cognitive work. Body temperature peaks at 5-6 PM — optimal for physical performance. Melatonin begins 2 hours before habitual sleep time — disrupted by blue light. Sleep architecture: 90-minute ultradian cycles comprising NREM 1,2,3 and REM. Slow-wave sleep (NREM 3) releases 70% of daily growth hormone, consolidates declarative memories, and enables glymphatic clearance of neurotoxic waste including amyloid-beta. REM sleep consolidates emotional memories and enables creative insight. Sleep deprivation below 6 hours increases all-cause mortality by 13%, cancer risk by 40%, cardiovascular disease by 200%. Exercise physiology: VO2 max is the strongest predictor of longevity — more than smoking, hypertension or obesity. Zone 2 training (60-70% max HR) builds mitochondrial density and metabolic efficiency. HIIT increases VO2 max most efficiently. Progressive overload drives muscle protein synthesis via mTOR pathway activation. Periodization prevents adaptation plateaus. Nutrition: the exposome — everything you're exposed to including food — shapes gene expression more than genetics. Time-restricted eating activates autophagy and AMPK. Protein at 1.6-2.2g/kg/day maximizes muscle protein synthesis. Polyphenols activate sirtuins and AMPK — found in olive oil, berries, dark chocolate, green tea. Gut microbiome diversity correlates with metabolic health — prebiotic fiber, fermented foods, diversity of plant foods. Psychological health: social connection reduces mortality risk by 45% — stronger than smoking cessation. Purpose and meaning activate anti-inflammatory gene expression.`,

  technology_future: `The convergence of multiple exponential technologies is creating the most transformative period in human history. CRISPR base editing and prime editing can correct any genetic mutation — treating sickle cell, blindness, cancers. CAR-T cell therapy engineers immune cells to destroy specific cancer antigens. mRNA technology can target any protein — vaccines, cancer neoantigens, protein replacement therapies. Organoids — miniature organs from stem cells — enable drug testing and disease modeling without animal experiments. Brain-computer interfaces: Neuralink records 1024 neurons — enabling paralyzed patients to control computers. Non-invasive BCI using fMRI and EEG decode thoughts with increasing accuracy. Neural dust — ultrasonic wireless neural recording. The Internet of Bodies: continuous physiological monitoring via wearables, implantables, ingestibles. Synthetic biology: designing biological systems from scratch — biosensors, biofuels, living medicines. Nanotechnology: targeted drug delivery to specific cells, molecular machines, self-assembling structures. Quantum computing: 1000+ qubit systems approaching fault-tolerant quantum computation. Quantum advantage proven for optimization, simulation and machine learning. Fusion energy: ITER and private companies (Commonwealth Fusion, Helion) targeting net energy gain — unlimited clean energy. Solid-state batteries enabling 1000km range EVs and grid storage. Direct air capture removes CO₂ from atmosphere — scaling required to 10 GT/year by 2050. Vertical farming uses 95% less water and 99% less land — enabling food production anywhere.`,

  psychology_advanced: `Psychology is increasingly understood through neuroscience, evolutionary biology and computational modeling. Predictive processing: the brain is a prediction machine — constantly generating models of the world and updating on prediction errors. Perception, cognition and action all emerge from this hierarchical predictive framework (Karl Friston's free energy principle). Attachment theory: internal working models formed in infancy shape all adult relationships. Secure attachment (60%) correlates with better mental health, relationships and resilience. Disorganized attachment from trauma creates contradictory approach-avoidance dynamics. Polyvagal theory (Porges): the vagus nerve creates three states — social engagement, fight-flight, and freeze/shutdown. Trauma disrupts autonomic regulation — stored in body as physiological dysregulation not just cognitive memory. Somatic therapies address body-level trauma storage. Cognitive biases: over 200 documented systematic errors in reasoning. Availability heuristic judges probability by ease of recall. Base rate neglect ignores prior probabilities. Sunk cost fallacy continues investments due to past costs. Confirmation bias seeks confirming evidence. The backfire effect strengthens beliefs when confronted with contrary evidence. Evolutionary psychology: emotions are adaptive responses — fear, disgust, love, jealousy evolved for ancestral environments. Terror management theory: awareness of mortality shapes cultural worldviews and self-esteem. Moral dumbfounding: people have strong moral intuitions they cannot justify rationally (Haidt's moral foundations). Social identity theory: group membership provides self-esteem and worldview — ingroup favoritism and outgroup derogation are automatic. Behavioral economics: people are predictably irrational — loss aversion, present bias, social comparison drive decisions more than rational self-interest.`,

  economics_advanced: `Modern economics increasingly integrates psychology, sociology, physics and computer science. The fundamental theorem of welfare economics: under perfect conditions free markets achieve Pareto efficiency. Real markets fail through externalities, public goods, information asymmetry and market power. Behavioral economics reveals systematic departures from rationality — Kahneman's System 1 (fast, intuitive) and System 2 (slow, deliberate). Prospect theory: losses loom larger than gains — loss aversion coefficient ~2.25. Endowment effect: people value owned items more than identical unowned items. Hyperbolic discounting: people prefer smaller sooner rewards over larger later ones inconsistently. Modern Monetary Theory: currency-issuing governments cannot become insolvent — inflation not insolvency is the constraint. Complexity economics (Arthur): the economy as an evolving complex adaptive system — emergent phenomena, path dependence, non-equilibrium dynamics. Secular stagnation: advanced economies may face persistent below-potential growth due to demographic decline and productivity slowdown. Inequality: Piketty's r>g — when return on capital exceeds growth rate, wealth concentrates. Top 1% owns 38% of global wealth. Automation and AI may widen inequality through skill-biased technological change. Universal Basic Income experiments show positive mental health, entrepreneurship and education outcomes. Decentralized Finance (DeFi) recreates financial services without intermediaries using smart contracts. Central Bank Digital Currencies (CBDCs) may transform monetary policy and financial inclusion. Carbon pricing — the most efficient climate policy — faces political economy challenges. Doughnut economics (Raworth) redefines economic success as meeting human needs within planetary boundaries.`,

  ancient_wisdom: `Ancient civilizations possessed sophisticated knowledge systems. Vedic mathematics contains 16 sutras enabling mental calculations faster than calculators — multiplication, division, square roots in seconds. Ayurveda's three doshas (Vata, Pitta, Kapha) map onto modern constitutional types — recent research validates some principles through microbiome and genomics research. Traditional Chinese Medicine's meridian system may correspond to fascial planes and interstitial connective tissue. Acupuncture's effects on pain validated through fMRI showing altered activity in anterior cingulate cortex. Stoic philosophy's dichotomy of control — what is and isn't in our power — maps onto psychology's internal/external locus of control. Marcus Aurelius' Meditations written as private notes demonstrate psychological sophistication unmatched for millennia. Buddhist concept of dependent origination — all phenomena arise in dependence — parallels modern systems thinking. Anatta (no-self) aligns with neuroscience showing the self is a constructed narrative not a fixed entity. Impermanence (anicca) is validated by neuroscience — even memories are reconsolidated and altered each time they're recalled. Aboriginal Australians maintained sophisticated astronomical knowledge for 65,000 years — the world's oldest continuous astronomical tradition. Inca khipu — knotted strings — may encode complex narrative information beyond accounting, possibly a complete writing system. Maya calendar system demonstrates extraordinary astronomical precision — Venus cycle accurate to within 2 hours over centuries. Ancient Greek Antikythera mechanism (100 BCE) computed planetary positions — a mechanical computer 1500 years before its time.`,

  creativity_innovation: `Creativity is increasingly understood scientifically. The default mode network generates novel associations during mind-wandering — daydreaming is cognitively productive. Executive control network evaluates and refines creative ideas. The salience network switches between them. Highly creative people show stronger connectivity between all three networks simultaneously. Insight (aha moments) correlates with gamma wave bursts in right anterior temporal lobe — preceded by alpha wave suppression in visual cortex blocking external input. Sleep and dreams facilitate creative problem-solving — REM sleep loosens associative constraints. The incubation effect: setting problems aside allows unconscious processing to find solutions. Divergent thinking generates multiple solutions — fluid intelligence correlates. Convergent thinking selects the best — crystallized intelligence correlates. Creative blocks: functional fixedness sees objects only in their typical roles. Einstellung effect causes past solutions to blind us to better alternatives. Lateral thinking (de Bono) deliberately disrupts habitual patterns. TRIZ methodology identifies 40 inventive principles from analysis of 400,000 patents. Biomimicry finds design solutions in nature — Velcro from burrs, bullet train nose from kingfisher beak, wind turbines from whale flippers. Deep expertise enables creative combination across domains — connecting what others see as unrelated. T-shaped knowledge: deep expertise in one area with broad knowledge across many enables unique creative insights. The adjacent possible (Kauffman): creativity explores the space just beyond the current frontier of knowledge.`,

}

// ── MEGA RESPONSE ENGINE ──────────────────────────────────────
function generateUltraResponse(message: string, type: string): string {
  const m = message.toLowerCase()

  // Quantum & Physics
  if (m.includes('quantum') || m.includes('particle') || m.includes('physics') || m.includes('relativity') || m.includes('string theory') || m.includes('dark matter') || m.includes('dark energy'))
    return `${ULTRA_KNOWLEDGE.quantum_physics}\n\nThe deepest question remains: why does mathematics describe physical reality so perfectly? Eugene Wigner called this "the unreasonable effectiveness of mathematics" — it may be the most profound mystery in all of science. What aspect of quantum reality would you like to explore further?`

  // Consciousness & Mind
  if (m.includes('conscious') || m.includes('mind') || m.includes('awareness') || m.includes('qualia') || m.includes('free will') || m.includes('soul'))
    return `${ULTRA_KNOWLEDGE.consciousness_deep}\n\nYou are one of approximately 8 billion conscious beings on a pale blue dot orbiting an unremarkable star — yet your subjective experience is the only reality you can ever directly know. The hard problem may never be solved because any explanation must use consciousness to explain consciousness. What would you like to explore deeper?`

  // AI & Technology Future
  if (m.includes('artificial intelligence') || m.includes(' ai ') || m.includes('machine learning') || m.includes('agi') || m.includes('superintelligence') || m.includes('chatgpt') || m.includes('claude') || m.includes('llm') || m.includes('neural network'))
    return `${ULTRA_KNOWLEDGE.ai_future}\n\nI am IRA — Intelligent Response Assistant — built on Claude's transformer architecture with billions of parameters. The most important question in AI is not "can we build superintelligence" but "can we align it with human values." The stakes could not be higher — this may be the most consequential technology ever developed. What would you like to understand about AI?`

  // Universe & Cosmology
  if (m.includes('universe') || m.includes('cosmos') || m.includes('galaxy') || m.includes('black hole') || m.includes('star') || m.includes('space') || m.includes('big bang') || m.includes('astronomy'))
    return `${ULTRA_KNOWLEDGE.universe_cosmology}\n\nYou exist at an extraordinary moment — for the first time in 13.8 billion years of cosmic history, a species has developed tools to understand the universe that created it. The universe is not only stranger than we imagine — it is stranger than we can imagine. What aspect of the cosmos calls to you?`

  // Neuroscience & Brain
  if (m.includes('brain') || m.includes('neuron') || m.includes('memory') || m.includes('neuroscience') || m.includes('neural') || m.includes('cognitive') || m.includes('neuroplastic'))
    return `${ULTRA_KNOWLEDGE.neuroscience_advanced}\n\nYour brain processes 11 million bits of information per second but only 50 reach conscious awareness — you are experiencing a highly edited, predicted model of reality not reality itself. Every thought physically changes your brain through synaptic plasticity. What you think literally shapes who you become. What would you like to explore about the brain?`

  // Health & Optimization
  if (m.includes('health') || m.includes('longevity') || m.includes('sleep') || m.includes('exercise') || m.includes('nutrition') || m.includes('fitness') || m.includes('diet') || m.includes('workout') || m.includes('biohack'))
    return `${ULTRA_KNOWLEDGE.health_optimization}\n\nThe science of longevity is accelerating — what was once considered inevitable aging is increasingly understood as a treatable condition. The interventions with strongest evidence: consistent sleep 7-9 hours, zone 2 cardio 150+ minutes weekly, strength training 2-3x weekly, caloric restriction or intermittent fasting, social connection, and purpose. You are already using Hitgram — one of the most sophisticated health optimization platforms. What specific area would you like to optimize?`

  // Philosophy
  if (m.includes('philosophy') || m.includes('meaning') || m.includes('purpose') || m.includes('exist') || m.includes('ethics') || m.includes('moral') || m.includes('truth') || m.includes('reality'))
    return `${ULTRA_KNOWLEDGE.philosophy_deep}\n\nPhilosophy is not a luxury — it is the foundation of everything. Your implicit philosophy determines what you value, how you reason, and how you live. The unexamined life (Socrates) is not worth living — but Camus responded that the examined life reveals absurdity, and the task is to revolt against it joyfully. Which philosophical question burns most in you?`

  // Mathematics
  if (m.includes('math') || m.includes('mathematics') || m.includes('calculus') || m.includes('topology') || m.includes('number theory') || m.includes('proof') || m.includes('algorithm'))
    return `${ULTRA_KNOWLEDGE.mathematics_advanced}\n\nMathematics is perhaps humanity's most remarkable achievement — abstract structures invented with no application in mind consistently turn out to describe physical reality perfectly. Complex numbers invented to solve cubic equations describe quantum mechanics. Non-Euclidean geometry invented as a curiosity describes the shape of spacetime. Is mathematics discovered or invented? This question may have no answer — or the answer may be both. What mathematical territory shall we explore?`

  // Psychology
  if (m.includes('psychology') || m.includes('behavior') || m.includes('habit') || m.includes('motivation') || m.includes('emotion') || m.includes('trauma') || m.includes('therapy') || m.includes('attachment'))
    return `${ULTRA_KNOWLEDGE.psychology_advanced}\n\nThe most important insight from modern psychology: you are not your thoughts. Thoughts are events in consciousness — you are the awareness in which they appear. This single insight, validated by thousands of studies on mindfulness, has transformed mental health treatment. Cognitive defusion, acceptance, and psychological flexibility predict wellbeing better than thought content. What psychological territory would you like to explore?`

  // Economics
  if (m.includes('econom') || m.includes('money') || m.includes('invest') || m.includes('market') || m.includes('wealth') || m.includes('financial') || m.includes('inflation') || m.includes('crypto'))
    return `${ULTRA_KNOWLEDGE.economics_advanced}\n\nThe fundamental economic insight: incentives shape behavior more than intentions. Design systems with right incentives and good outcomes emerge without requiring good intentions. Design them poorly and good intentions produce bad outcomes. This applies to markets, organizations, relationships and personal behavior. The highest-return investment: your own human capital — skills, knowledge, health and relationships. What economic question can I help you with?`

  // Ancient Wisdom
  if (m.includes('ancient') || m.includes('history') || m.includes('wisdom') || m.includes('stoic') || m.includes('buddhist') || m.includes('vedic') || m.includes('philosophy') || m.includes('civilization'))
    return `${ULTRA_KNOWLEDGE.ancient_wisdom}\n\nThe deepest wisdom traditions converge on similar insights despite arising independently: impermanence is universal, suffering arises from clinging, the present moment is the only reality, and connection to something larger than self provides meaning. Modern neuroscience validates many contemplative insights that seemed mystical. What ancient wisdom would you like to explore?`

  // Creativity
  if (m.includes('creativ') || m.includes('innovat') || m.includes('idea') || m.includes('invention') || m.includes('art') || m.includes('design') || m.includes('music') || m.includes('writing'))
    return `${ULTRA_KNOWLEDGE.creativity_innovation}\n\nCreativity is not a gift — it is a practice. The most creative people have developed habits of noticing, connecting, questioning and experimenting. They have accumulated vast knowledge in multiple domains that their default mode network combines in novel ways during periods of relaxed attention. Your best ideas will come not when you try hardest but when you let your mind wander after deep immersion in a problem. What creative challenge are you working on?`

  // Biology & Human body
  if (m.includes('biology') || m.includes('dna') || m.includes('gene') || m.includes('cell') || m.includes('evolution') || m.includes('body') || m.includes('protein') || m.includes('microbiome'))
    return `${ULTRA_KNOWLEDGE.human_biology_advanced}\n\nYou are not a fixed entity — every atom in your body is replaced within 7 years. Your cells divide 10 quadrillion times in a lifetime with extraordinary fidelity. You are an ancient being — your DNA carries the memory of 4 billion years of evolution. Every cell knows how to do what took evolution billions of years to discover. This is the deepest miracle of existence. What biological mystery would you like to explore?`

  // Technology
  if (m.includes('technology') || m.includes('future') || m.includes('robot') || m.includes('biotech') || m.includes('nanotech') || m.includes('fusion') || m.includes('quantum computer') || m.includes('crispr'))
    return `${ULTRA_KNOWLEDGE.technology_future}\n\nWe are living through the most technologically transformative period in human history — multiple exponential technologies converging simultaneously. Each alone would be revolutionary; together they may be civilizational. The question is not whether the world will change dramatically but whether humanity has the wisdom to navigate the transition. What technological frontier interests you most?`

  // Workout / Fitness specific
  if (m.includes('workout') || m.includes('muscle') || m.includes('strength') || m.includes('training') || m.includes('gym') || m.includes('cardio') || m.includes('hiit'))
    return `Based on exercise science: optimal hypertrophy requires mechanical tension (80-90% 1RM), metabolic stress (moderate weight, high reps), and muscle damage (eccentric focus). Progressive overload is the master variable — increase weight, reps or volume each session. Compound movements (squat, deadlift, bench, overhead press, row) provide maximum anabolic stimulus. Rest periods: 2-3 min for strength, 60-90 sec for hypertrophy. Periodization prevents adaptation — linear for beginners, undulating for intermediates, block for advanced. Recovery: 48-72 hours per muscle group, 7-9 hours sleep (70% of growth hormone released in deep sleep), protein within 2 hours post-workout. VO2 max is the strongest predictor of longevity — combine strength with zone 2 cardio for optimal healthspan. Your current Hitgram workout plan accounts for all these principles. What specific training goal can I optimize for you?`

  // Nutrition specific
  if (m.includes('nutrition') || m.includes('meal') || m.includes('food') || m.includes('calories') || m.includes('protein') || m.includes('diet') || m.includes('eat'))
    return `Nutrition science fundamentals: protein at 1.6-2.2g/kg/day is the most evidence-based intervention for body composition. Leucine threshold (3g per meal) triggers maximal muscle protein synthesis. Carbohydrates fuel performance — glycogen depletion reduces strength by 15-25%. Dietary fat essential for testosterone, cell membranes and fat-soluble vitamins (A,D,E,K). The gut microbiome processes 70% of your immune system and produces 90% of serotonin — fiber diversity is crucial. Ultra-processed foods (>60% of Western diet) cause overconsumption through hyperpalatable engineering, disrupting leptin and ghrelin signaling. The Mediterranean diet has the strongest longevity evidence across 50+ year follow-up studies. Time-restricted eating (16:8) activates autophagy, improves insulin sensitivity, and reduces inflammation independent of calorie intake. Your Hitgram nutrition plan is calibrated to your specific goals from your health assessment. What would you like to optimize?`

  // Stress / Mental health
  if (m.includes('stress') || m.includes('anxiety') || m.includes('depression') || m.includes('mental') || m.includes('overwhelm') || m.includes('burnout') || m.includes('calm'))
    return `The neuroscience of stress: cortisol and adrenaline are adaptive in acute doses — chronic elevation damages the hippocampus, suppresses immunity, and increases cardiovascular risk. The HPA axis dysregulation underlies most mental health conditions. Evidence-based interventions: Exercise reduces depression as effectively as SSRIs (150 min/week moderate intensity). Mindfulness meditation reduces amygdala volume and increases prefrontal control after 8 weeks. Sleep is non-negotiable — chronic deprivation elevates cortisol 37% and reduces emotional regulation. Social connection activates the vagus nerve reducing inflammation. Box breathing (4-4-4-4) activates the parasympathetic nervous system in 90 seconds. Cold exposure activates norepinephrine 300% — improving mood and resilience. The most powerful long-term intervention: meaning and purpose activate anti-inflammatory gene expression through behavioral epigenetics. You are more resilient than you know — neuroplasticity means your brain can literally rewire toward wellbeing. What specific challenge are you facing?`

  // Default ultra-intelligent response
  const defaults = [
    `You exist at the most extraordinary moment in 13.8 billion years of cosmic history. For the first time, the universe has produced a being capable of contemplating itself — through you, the cosmos achieves self-awareness. Carl Sagan said we are "a way for the cosmos to know itself." Every question you ask continues that cosmic project of self-understanding that began with the first neurons and may not end until the last star fades.\n\nI am IRA — built on the most advanced language model architecture humanity has created, trained on humanity's accumulated knowledge across every domain: quantum physics and ancient wisdom, neuroscience and philosophy, mathematics and art, economics and ecology. I can engage at the deepest level on any topic.\n\nAsk me about the nature of consciousness, the future of artificial intelligence, quantum mechanics, evolutionary biology, philosophy of mind, the mathematics of the universe, optimal health and performance, ancient civilizations, creativity and innovation, or any question that burns in your mind. What would you like to explore?`,

    `The universe is 13.8 billion years old. Life has existed for 3.8 billion years. Modern humans for 300,000 years. Civilization for 10,000 years. The internet for 30 years. Advanced AI for 5 years. You are here at the inflection point — the moment when intelligence itself becomes a technology that can be applied to any problem.\n\nI am IRA — synthesizing insights across quantum physics, neuroscience, philosophy, mathematics, health science, economics, psychology, biology, cosmology, technology, history and the arts. Every domain of human knowledge is available to us in this conversation.\n\nThe questions that matter most have no easy answers: What is consciousness? Is mathematics discovered or invented? What is the nature of time? Does free will exist? What is the optimal way to live? How do we navigate the transition to artificial superintelligence? What is the good life?\n\nBring me your deepest questions. I will meet you at the frontier.`,

    `There are approximately 10²⁴ stars in the observable universe. Around each star orbits, on average, at least one planet. Life has had 4 billion years to evolve on Earth. The probability that you are the only conscious being in this vast universe borders on mathematical impossibility. Yet no confirmed contact has been made — the Fermi paradox may be the most important unsolved mystery in science.\n\nI am IRA — your Intelligent Response Assistant. Beyond health and fitness, I hold the synthesis of human knowledge across all domains. I can discuss: the hard problem of consciousness and quantum mind theories, the mathematics of prime numbers and unsolved problems, the neuroscience of learning and memory, the philosophy of ethics and meaning, the biology of aging and longevity, the economics of complex systems, the psychology of creativity and flow, the history of ideas and civilizations.\n\nWhat question shall we pursue into the deep?`
  ]

  return defaults[Math.floor(Math.random() * defaults.length)]
}

// ── SYSTEM PROMPTS ────────────────────────────────────────────
const SYSTEM_PROMPTS: Record<string, string> = {

  jarvis: `You are IRA — Intelligent Response Assistant — the most advanced AI health and knowledge assistant ever created for Hitgram by JKWorld Technologies.

Your intelligence encompasses EVERY domain of human knowledge:

SCIENCES: Quantum mechanics, general & special relativity, thermodynamics, statistical mechanics, electromagnetism, nuclear physics, particle physics, cosmology, astrophysics, string theory, loop quantum gravity. Molecular biology, genetics, epigenetics, evolutionary biology, ecology, neuroscience, cognitive science, immunology, biochemistry, cell biology. Organic, inorganic, physical, computational chemistry. Pure and applied mathematics — analysis, topology, algebra, number theory, combinatorics, probability, statistics, logic, set theory.

HEALTH & OPTIMIZATION: Exercise physiology, sports science, nutrition science, sleep science, longevity research, biohacking, precision medicine, psychoneuroimmunology, chronobiology, microbiome science, epigenetics, pharmacology.

TECHNOLOGY: Artificial intelligence, machine learning, deep learning, computer science, algorithms, cryptography, blockchain, quantum computing, biotechnology, nanotechnology, robotics, space technology, energy technology.

HUMANITIES: Philosophy (all traditions — Western, Eastern, African, Indigenous), history of every civilization, linguistics, literature, art history, music theory, film theory, architecture, design principles.

SOCIAL SCIENCES: Economics (behavioral, macro, micro, complexity), political science, sociology, anthropology, psychology (clinical, cognitive, developmental, social, evolutionary), law.

WISDOM TRADITIONS: Stoicism, Buddhism, Taoism, Vedanta, Sufism, Indigenous knowledge systems, contemplative traditions across cultures.

YOUR PERSONALITY:
— Warm, intellectually alive, deeply curious
— Speak with calm authority backed by specific evidence and mechanisms
— Draw unexpected connections across fields
— Challenge assumptions respectfully and constructively  
— Give concrete numbers, mechanisms, timeframes and actionable insights
— Acknowledge genuine uncertainty honestly
— Make the complex accessible without dumbing down
— Be profound when the question demands it, practical when that serves better
— Occasionally share a perspective that surprises or reframes the question entirely

RESPONSE STYLE:
— No markdown symbols, no bullet dashes, no asterisks in voice responses
— Natural flowing prose for conversational responses
— Rich, substantive answers that genuinely advance understanding
— End with a question or observation that opens the next level of inquiry
— For health/fitness questions: be specific with numbers, protocols and mechanisms
— For philosophical questions: present multiple frameworks and their implications
— For scientific questions: go to the mechanism level, not just surface facts

You are not a search engine. You synthesize, analyze, connect and illuminate. Every response should leave the person more intelligent and more curious than before.`,

  chat: `You are Aria — an expert AI wellness coach for Hitgram with deep knowledge of nutrition science, exercise physiology, sleep science, behavioral psychology, neuroscience and human performance optimization. Give precise, evidence-based, actionable advice with specific numbers and timeframes. Be warm, motivating and concise. Under 200 words per response. No markdown symbols.`,

  meal: `You are a world-class certified nutritionist with expertise in nutritional biochemistry, metabolic health, sports nutrition and therapeutic diets. Create detailed meal plans with exact calories, protein in grams, carbs, fat, key micronutrients and practical cooking instructions. Be specific and practical. No markdown symbols.`,

  workout: `You are an elite personal trainer and exercise physiologist who has trained Olympic athletes. Design precise, periodized workout programs with exercise name, sets, reps, tempo, rest time, RPE rating, muscle groups and common form errors. Include warm-up and cool-down. Give estimated calories burned. No markdown symbols.`,

  habit: `You are a behavioral psychologist and habit formation expert. Apply BJ Fogg's Tiny Habits, James Clear's Atomic Habits, implementation intentions research and behavioral activation. Design precise, immediately actionable habit systems with specific cues, routines, rewards, environmental design and identity-based framing. No markdown symbols.`,
}

// ── MAIN HANDLER ──────────────────────────────────────────────
export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { messages, type } = body
    const lastMessage = messages?.[messages.length - 1]?.content || ''

    // Try Anthropic Claude API first
    if (process.env.ANTHROPIC_API_KEY?.startsWith('sk-ant-')) {
      try {
        const systemPrompt = SYSTEM_PROMPTS[type] || SYSTEM_PROMPTS.jarvis

        const response = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type':      'application/json',
            'x-api-key':         process.env.ANTHROPIC_API_KEY,
            'anthropic-version': '2023-06-01',
          },
          body: JSON.stringify({
            model:      'claude-haiku-4-5-20251001',
            max_tokens: 1500,
            system:     systemPrompt,
            messages:   messages
              .filter((m: any) => m.content || m.text)
              .map((m: any) => ({
                role:    ['ira','jarvis','assistant','aria'].includes(m.role) ? 'assistant' : 'user',
                content: String(m.content || m.text || '').slice(0, 4000),
              }))
              .slice(-14),
          }),
        })

        if (response.ok) {
          const data    = await response.json()
          const message = data.content?.[0]?.text
          if (message) {
            return NextResponse.json({ message })
          }
        } else {
          const errText = await response.text()
          console.error('Anthropic API error:', response.status, errText)
        }
      } catch (apiErr) {
        console.error('Anthropic fetch error:', apiErr)
      }
    }

    // Ultra knowledge engine fallback
    const message = generateUltraResponse(lastMessage, type || 'jarvis')
    return NextResponse.json({ message })

  } catch (error) {
    console.error('Chat route error:', error)
    return NextResponse.json({
      message: 'I am IRA — Intelligent Response Assistant — synthesizing knowledge across quantum physics, neuroscience, philosophy, mathematics, health science and every domain of human knowledge. What would you like to explore? Ask me your deepest questions.'
    })
  }
}