import { NextResponse } from 'next/server'

// ── DEEP KNOWLEDGE BASE ───────────────────────────────────────
const KNOWLEDGE: Record<string, Record<string, string>> = {

  science: {
    physics: "Physics encompasses classical mechanics by Newton describing F=ma and gravitational attraction between masses. Einstein revolutionized physics with special relativity where E=mc² showing mass-energy equivalence, and general relativity describing gravity as spacetime curvature. Quantum mechanics reveals particles exist in superposition until observed, with Heisenberg uncertainty principle showing position and momentum cannot both be precisely known. Standard Model unifies electromagnetic, weak and strong nuclear forces through quantum field theory. String theory proposes reality consists of 1-dimensional vibrating strings in 10-11 dimensions. Dark matter constitutes 27% of universe and dark energy 68%, both completely unknown in composition. Hawking radiation describes black holes slowly evaporating through quantum effects. The Big Bang 13.8 billion years ago began space, time, matter and energy from a singularity of infinite density.",
    chemistry: "Chemistry studies matter composition and transformation. Periodic table organizes 118 elements by atomic number and electron configuration. Chemical bonds form through electron sharing (covalent), transfer (ionic) or metallic bonding. Organic chemistry focuses on carbon compounds — life's molecular foundation. Biochemistry studies proteins (amino acid chains folded into 3D structures), DNA (double helix of nucleotide base pairs A-T and G-C), RNA (messenger, transfer, ribosomal), enzymes (biological catalysts lowering activation energy), lipids, carbohydrates and metabolic pathways. Thermodynamics governs energy in reactions — enthalpy, entropy and Gibbs free energy determine spontaneity. Quantum chemistry models electron orbitals and molecular orbital theory explains bonding. Nanotechnology manipulates matter at 1-100 nanometer scale.",
    biology: "Life's fundamental unit is the cell — prokaryotic (bacteria, archaea, no nucleus) or eukaryotic (plants, animals, fungi, protists, with nucleus and organelles). DNA stores genetic information in codons read by ribosomes to synthesize proteins. Evolution by natural selection (Darwin) explains biodiversity — traits increasing reproductive success spread through populations. Human body has 37 trillion cells, 206 bones, 640 muscles, 79 organs. The brain has 86 billion neurons each making 7,000 synaptic connections. Immune system uses T-cells, B-cells, natural killer cells, antibodies, complement proteins and inflammation to fight pathogens. CRISPR-Cas9 enables precise gene editing. Epigenetics shows gene expression changes without DNA sequence changes. Microbiome — 38 trillion microbes in human gut — profoundly affects health, immunity and even cognition.",
    mathematics: "Mathematics is the language of the universe. Calculus (Newton, Leibniz) provides derivatives measuring instantaneous rates and integrals measuring accumulation. Linear algebra studies vector spaces and linear transformations fundamental to machine learning. Number theory explores prime numbers, Riemann hypothesis (unsolved), Goldbach's conjecture. Topology studies shapes preserved under continuous deformation. Chaos theory shows deterministic systems produce unpredictable behavior — butterfly effect. Gödel's incompleteness theorems prove any sufficiently powerful formal system contains true statements unprovable within that system. P vs NP is the greatest unsolved problem in computer science. Fermat's Last Theorem proved by Andrew Wiles in 1995 after 358 years. Euler's identity e^(iπ)+1=0 connects five fundamental mathematical constants.",
    astronomy: "Observable universe spans 93 billion light-years containing 2 trillion galaxies each with hundreds of billions of stars. Milky Way is a barred spiral galaxy 100,000 light-years across containing 200-400 billion stars including our Sun — a G-type main sequence star 4.6 billion years old. Solar system has 8 planets, 5 dwarf planets, asteroid belt, Kuiper belt and Oort cloud. Black holes form from massive star collapse — stellar mass (3-100 solar masses), supermassive (millions to billions solar masses, found in galactic centers). Neutron stars are incredibly dense — teaspoon weighs 10 million tons. Pulsars emit precise radio pulse beams. Gravitational waves detected by LIGO in 2015 confirmed Einstein's 1916 prediction. James Webb Space Telescope observes galaxies from 13.6 billion years ago.",
  },

  technology: {
    ai: "Artificial intelligence has entered a transformative era. Large Language Models (LLMs) like GPT-4, Claude, Gemini are transformer architectures with billions to trillions of parameters trained on vast text corpora using self-supervised learning. Transformer architecture uses self-attention mechanism allowing parallel processing and capturing long-range dependencies. Reinforcement Learning from Human Feedback (RLHF) aligns models with human preferences. Diffusion models (Stable Diffusion, DALL-E, Midjourney) generate images by learning to reverse a noise-adding process. Multimodal AI processes text, images, audio, video simultaneously. Neural networks are loosely inspired by biological neurons — layers of weighted connections trained by backpropagation and gradient descent. Computer vision uses convolutional neural networks for image recognition. Robotics combines AI with mechanical systems for autonomous action. AGI (artificial general intelligence) remains the frontier goal — human-level reasoning across all domains.",
    programming: "Programming languages serve different paradigms. Python dominates data science and AI with libraries NumPy, Pandas, TensorFlow, PyTorch, Scikit-learn. JavaScript/TypeScript powers web development with React, Next.js, Vue, Angular frameworks. Rust provides memory safety without garbage collection for systems programming. Go excels in concurrent server applications. C and C++ remain essential for performance-critical systems, operating systems and embedded software. Java and Kotlin dominate Android development. Swift powers iOS development. SQL manages relational databases while NoSQL databases like MongoDB, Redis, Cassandra handle unstructured data. Kubernetes orchestrates containerized applications. Docker packages applications with dependencies. GraphQL provides flexible API queries. WebAssembly enables near-native performance in browsers. Blockchain technology enables decentralized trustless systems.",
    medicine: "Modern medicine has achieved remarkable milestones. mRNA vaccines (Moderna, Pfizer-BioNTech) demonstrated the technology's potential during COVID-19 and now target cancer. Immunotherapy trains the immune system to recognize and destroy cancer cells — checkpoint inhibitors block PD-1/PD-L1 axis. CAR-T cell therapy engineers patient's T-cells to attack specific cancers. CRISPR gene therapy treats sickle cell disease, beta thalassemia, and blindness. Liquid biopsies detect cancer DNA in bloodstream for early diagnosis. Brain-computer interfaces (Neuralink) enable paralyzed patients to control computers with thoughts. Organoids are miniature organs grown from stem cells for drug testing. Precision medicine tailors treatment to individual genetic profiles. Antibiotic resistance is a critical global threat requiring new antimicrobial strategies. The human gut microbiome increasingly linked to mental health through gut-brain axis.",
    space: "Space exploration has entered a new commercial era. SpaceX Starship is the most powerful rocket ever built targeting Mars colonization. Artemis program returns humans to the Moon as a stepping stone to Mars. Commercial space stations will replace ISS retiring around 2030. Satellite internet constellations (Starlink, OneWeb) provide global broadband coverage. Mars has been explored by rovers (Curiosity, Perseverance) finding evidence of ancient water and organic molecules. Europa and Enceladus have subsurface oceans considered prime candidates for extraterrestrial life. Nuclear thermal propulsion could cut Mars travel time to 3-4 months. Space manufacturing in microgravity enables perfect fiber optics and pharmaceutical crystals. Asteroid mining could provide trillions in rare minerals. Terraforming Mars theoretical proposals involve greenhouse gas release and orbital mirrors.",
  },

  health: {
    fitness: "Exercise physiology reveals muscle hypertrophy requires mechanical tension, metabolic stress and muscle damage — triggering mTOR pathway activating protein synthesis. Progressive overload principle mandates systematic increase in volume, intensity or frequency. Compound lifts (squat, deadlift, bench press, overhead press) stimulate maximum anabolic hormone release. HIIT improves VO2 max and metabolic rate more efficiently than steady-state cardio through EPOC effect — excess post-exercise oxygen consumption elevating metabolism 12-24 hours post-workout. Periodization cycles training stimulus through accumulation, intensification and realization phases. Deload weeks every 4-6 weeks prevent overtraining by reducing volume 40-60%. Recovery requires 48-72 hours between training same muscle groups. Heart rate training zones: Zone 2 (60-70% max HR) builds aerobic base and mitochondrial density. Muscle fiber types: slow-twitch (Type I) for endurance, fast-twitch (Type II) for power and strength.",
    nutrition: "Nutrition science reveals optimal health requires macronutrient and micronutrient balance. Protein at 1.6-2.2g per kg bodyweight maximizes muscle protein synthesis — leucine threshold (3g per meal) triggers mTOR. Carbohydrates are the primary fuel source — glycemic index measures blood glucose response. Dietary fat is essential for hormone production, cell membrane integrity and fat-soluble vitamin absorption. Micronutrients — vitamins and minerals — serve as enzyme cofactors for thousands of biochemical reactions. Gut microbiome diversity correlates with metabolic health — fermented foods, diverse plant intake, prebiotic fiber promote beneficial bacteria. Intermittent fasting triggers autophagy — cellular cleanup removing damaged proteins. Caloric restriction extends lifespan in multiple organisms through AMPK activation and reduced IGF-1 signaling. Mediterranean diet consistently shows strongest evidence for longevity and cardiovascular health. Omega-3 fatty acids EPA and DHA reduce inflammation through prostaglandin and leukotriene pathway modulation.",
    sleep: "Sleep is the most powerful free performance enhancer available. Circadian rhythm is orchestrated by suprachiasmatic nucleus responding to light — blue light suppresses melatonin secretion delaying sleep onset. Sleep architecture cycles through 90-minute ultradian rhythms comprising NREM stages 1-3 (deep slow wave sleep) and REM sleep. Slow wave sleep releases 70% of daily growth hormone, consolidates declarative memories, and clears metabolic waste via glymphatic system — including amyloid-beta associated with Alzheimer's. REM sleep processes emotional memories and enables creative insight. Chronic sleep deprivation below 7 hours increases dementia risk, cardiovascular disease, metabolic syndrome, and immune dysfunction. Adenosine accumulates during wakefulness creating sleep pressure — caffeine blocks adenosine receptors. Optimal bedroom temperature 65-68°F (18-20°C). Sleep inertia lasts 15-30 minutes after waking explaining grogginess.",
    mental_health: "Mental health is foundational to overall wellbeing. Neurotransmitter systems regulate mood and cognition: serotonin (mood, sleep, appetite), dopamine (reward, motivation, movement), norepinephrine (alertness, focus, stress response), GABA (inhibitory calming), glutamate (excitatory learning and memory), acetylcholine (memory, muscle contraction). Depression involves neuroinflammation, HPA axis dysregulation, reduced neuroplasticity and hippocampal volume. Exercise is the most evidence-based intervention for depression — BDNF (Brain-Derived Neurotrophic Factor) increases 200-300% after intense exercise promoting neurogenesis. Cognitive Behavioral Therapy (CBT) is gold standard psychotherapy — restructuring maladaptive thought patterns. Mindfulness meditation strengthens prefrontal cortex, reduces amygdala reactivity, increases gray matter density. Trauma stored in body as physiological dysregulation — somatic therapies (EMDR, Somatic Experiencing) process trauma through body. Social connection is as important for health as diet and exercise — loneliness increases mortality risk by 26%.",
  },

  philosophy: {
    existence: "Philosophy of existence asks the deepest questions humans face. Ontology studies the nature of being — what exists and why. Descartes' cogito ergo sum (I think therefore I am) establishes consciousness as the one certainty. Existentialism (Sartre, Heidegger, Camus) argues existence precedes essence — we create our own meaning in an inherently meaningless universe. Absurdism (Camus) acknowledges the conflict between human desire for meaning and universe's silence. Nihilism denies objective meaning, value or truth. Stoicism (Marcus Aurelius, Epictetus, Seneca) teaches focus only on what is within your control, accept the rest with equanimity. Buddhist philosophy teaches dukkha (suffering arises from attachment), impermanence of all phenomena, and the middle path between indulgence and asceticism. Taoism seeks harmony with the natural order (Tao) through wu wei — effortless non-striving action. Plato's allegory of the cave describes humans mistaking shadows for reality, philosophy as the journey toward the sun (truth).",
    ethics: "Ethical philosophy provides frameworks for moral reasoning. Consequentialism (Utilitarianism — Bentham, Mill) judges actions by outcomes — greatest good for greatest number. Deontological ethics (Kant) judges actions by adherence to universal moral rules — categorical imperative: act only according to principles you would will to be universal law. Virtue ethics (Aristotle) focuses on character development — eudaimonia (flourishing) achieved through cultivating virtues (courage, justice, temperance, wisdom). Care ethics emphasizes relationships and context over universal rules. Contractualism (Rawls) derives justice from what rational people would choose behind a veil of ignorance. The trolley problem illustrates tension between action and inaction in moral decision-making. Effective altruism applies evidence and reason to maximize positive impact. Moral realism argues objective moral truths exist independent of minds while anti-realism argues morality is constructed.",
    consciousness: "The hard problem of consciousness (Chalmers) asks why physical processes give rise to subjective experience — qualia. Integrated Information Theory (Tononi) quantifies consciousness as phi — measure of integrated information. Global Workspace Theory (Baars, Dehaene) describes consciousness as broadcasting information to multiple brain systems. Panpsychism argues consciousness is a fundamental feature of reality — every system has some form of experience. Illusionism (Frankish) proposes phenomenal consciousness is itself an introspective illusion. Free will debates persist — compatibilists argue free will and determinism coexist, hard determinists deny genuine choice, libertarians argue quantum indeterminacy creates space for genuine agency. Neuroscience identifies neural correlates of consciousness in thalamo-cortical circuits but cannot explain why these correlate with experience. Dreams provide window into consciousness — default mode network active during dreaming, confabulation and reality monitoring temporarily suspended.",
  },

  history: {
    ancient: "Ancient civilizations laid civilization's foundation. Sumer (3500 BCE, Mesopotamia) created cuneiform writing, the wheel, city-states and legal codes. Ancient Egypt built pyramids as tombs — Great Pyramid of Giza aligns precisely with cardinal directions requiring sophisticated astronomical knowledge. Ancient Greece birthed democracy, philosophy (Socrates, Plato, Aristotle), theater, mathematics (Pythagoras, Euclid, Archimedes) and Olympic games. Roman Empire at its peak controlled 5 million km² and 70 million people — contributions include Roman law, engineering (aqueducts, roads, concrete), Latin language that evolved into Romance languages. Ancient China invented paper, printing press, gunpowder, compass, silk. Indus Valley civilization had advanced urban planning with sophisticated drainage systems. Maya civilization developed highly accurate calendar, zero concept, advanced astronomy. Ancient Egypt had sophisticated medicine including brain surgery, antibiotics from honey and mold 3000 years before penicillin's discovery.",
    modern: "Modern history shaped the contemporary world. Industrial Revolution (1760-1840) transformed from agricultural to industrial society through steam power, textile manufacturing and railroad networks. French Revolution (1789) dismantled feudalism and spread Enlightenment ideals of liberty, equality and fraternity. American Revolution (1776) established first modern democracy based on Enlightenment principles. World War I (1914-1918) killed 20 million — trench warfare, poison gas and machine guns ended 19th century optimism. World War II (1939-1945) killed 70-85 million including Holocaust of 6 million Jews and systematic genocide of other groups. Cold War nuclear arms race between US and USSR brought humanity to brink of destruction during Cuban Missile Crisis 1962. Moon landing 1969 showed human potential for achieving seemingly impossible. Fall of Soviet Union 1991 ended bipolar world order. September 11 2001 transformed global security. COVID-19 pandemic 2020-2022 killed 7 million demonstrating global vulnerability to biological threats.",
  },

  arts_culture: {
    music: "Music theory studies the mathematical relationships between sounds. Western music divides octave into 12 semitones — equal temperament allows transposition to any key. Harmony arises from consonant frequency ratios — perfect fifth is 3:2 ratio. Counterpoint (Bach) layers independent melodic voices following strict rules. Rhythm divides time into patterns of stressed and unstressed beats organized into meters. Jazz emerged from African American musical traditions blending blues, ragtime and European harmony — improvisation over chord progressions called changes. Rock and roll synthesized blues, gospel and country — electric guitar amplification created new sonic possibilities. Electronic music uses synthesis (subtractive, additive, FM, wavetable), sampling and digital signal processing. Hip-hop emerged from Bronx in 1970s — turntablism, sampling, MCing, breakdancing, graffiti. The circle of fifths shows harmonic relationships between all 12 major and minor keys.",
    literature: "Literature explores the full range of human experience through language. Homer's Iliad and Odyssey (8th century BCE) are foundational epics of Western tradition. Shakespeare (1564-1616) explored power, love, jealousy, ambition and mortality with unmatched psychological insight in 37 plays. Modernist literature (Joyce, Woolf, Faulkner) experimented with stream of consciousness and fragmented narrative. Magic realism (García Márquez, Borges) blends mundane reality with magical elements. Existentialist literature (Sartre, Camus, Kafka) grapples with absurdity and meaning-making. Postcolonial literature (Achebe, Rushdie, Morrison) examines colonialism's lasting trauma and identity formation. Science fiction (Asimov, Dick, Le Guin) uses speculative technology to examine contemporary social issues. Poetry compresses language to maximum emotional density — meter, rhyme, imagery, metaphor, enjambment all serve meaning.",
  },

  economics: {
    macro: "Macroeconomics studies economy-wide phenomena. GDP measures total economic output — consumption plus investment plus government spending plus net exports. Inflation erodes purchasing power — Federal Reserve targets 2% as optimal balancing growth and stability. Interest rates are economy's primary lever — lower rates stimulate borrowing and spending, higher rates cool inflation. Keynesian economics advocates government spending during recessions to stimulate aggregate demand. Monetarism (Friedman) emphasizes controlling money supply to control inflation. Supply-side economics focuses on reducing regulatory and tax burden on producers. Modern Monetary Theory argues currency-issuing governments cannot become insolvent in their own currency. Quantitative easing creates money to purchase assets expanding money supply. Fiscal policy (government spending, taxation) and monetary policy (interest rates, money supply) work together. Global trade benefits from comparative advantage — nations specialize in what they produce most efficiently.",
    markets: "Financial markets facilitate capital allocation across economy. Stock markets provide equity financing — share price reflects discounted future cash flows in efficient market hypothesis. Bond markets price debt — yield and price move inversely, yield curve normally slopes upward reflecting time value of money. Derivatives (options, futures, swaps) hedge risk or provide leverage. Cryptocurrencies use blockchain technology — Bitcoin's proof-of-work consensus mechanism and limited supply of 21 million coins creates digital scarcity. DeFi (decentralized finance) recreates financial services without intermediaries using smart contracts on Ethereum. Behavioral economics (Kahneman, Thaler) reveals systematic cognitive biases distorting financial decisions — loss aversion, anchoring, availability heuristic. Venture capital funds early stage companies in exchange for equity. Private equity acquires and restructures mature companies. Hedge funds employ sophisticated strategies including long-short, global macro and quantitative approaches.",
  },

  psychology: {
    cognitive: "Cognitive psychology studies mental processes. Working memory holds 7±2 chunks of information for short-term manipulation — prefrontal cortex dependent. Long-term memory divides into declarative (episodic — personal events, semantic — general knowledge) and non-declarative (procedural skills, conditioning). Memory consolidation occurs during sleep — hippocampus transfers memories to neocortex during slow wave sleep. Attention is a limited resource — dual task interference occurs when two tasks compete for same cognitive resources. Cognitive load theory has implications for learning — intrinsic (complexity), extraneous (poor design) and germane (schema formation) loads. Heuristics are mental shortcuts — availability heuristic judges probability by ease of recall, representativeness by similarity to prototype. Confirmation bias leads to seeking information confirming existing beliefs. Cognitive dissonance creates discomfort when beliefs and behaviors conflict — resolved by changing beliefs or rationalizing behavior.",
    developmental: "Developmental psychology traces human psychological development across lifespan. Piaget's stages of cognitive development: sensorimotor (0-2, object permanence), preoperational (2-7, symbolic thinking, egocentrism), concrete operational (7-11, logical thinking about concrete objects), formal operational (12+, abstract reasoning). Vygotsky's zone of proximal development describes learning that occurs with guidance beyond current independent capability. Attachment theory (Bowlby, Ainsworth) shows early caregiver relationships create internal working models shaping all future relationships — secure, anxious, avoidant, disorganized attachment styles. Erikson's psychosocial stages describe challenges across eight life stages from trust vs mistrust (infancy) to integrity vs despair (late adulthood). Adverse childhood experiences (ACEs) create lasting physiological and psychological dysregulation increasing disease risk across lifespan. Resilience factors include secure attachment, self-regulation skills, community support and sense of meaning.",
  },

  environment: {
    climate: "Climate change is the defining challenge of our era. Earth's average temperature has risen 1.2°C since pre-industrial times — greenhouse gases (CO2, methane, nitrous oxide, water vapor) trap outgoing longwave radiation warming planet. CO2 levels at 420 ppm highest in 3 million years — primarily from fossil fuel combustion, deforestation and industrial processes. Feedback loops amplify warming: Arctic ice albedo feedback (less ice absorbs more heat), permafrost methane release, water vapor amplification. IPCC warns 1.5°C limit requires halving emissions by 2030 and net-zero by 2050. Renewable energy (solar, wind, hydroelectric, geothermal) now cheaper than fossil fuels in most markets. Electric vehicle adoption, green hydrogen, carbon capture and storage, regenerative agriculture and nuclear power all necessary components of decarbonization. Biodiversity loss — sixth mass extinction — threatens ecosystem services worth $125 trillion annually.",
    ecology: "Ecology studies relationships between organisms and their environments. Ecosystem services include pollination (valued at $235 billion annually), water purification, carbon sequestration, climate regulation and soil formation. Trophic cascades show removal of keystone predators collapses ecosystems — wolf reintroduction to Yellowstone changed river courses through trophic cascade effects. Nitrogen and phosphorus cycles — human disruption through agricultural fertilizers creating dead zones in oceans. Plastic pollution — 8 million tons enters ocean annually — microplastics now found in human blood, placentas, lungs and brains. Deforestation eliminates 15 billion trees annually — Amazon losing 10,000 sq km per year. Ocean acidification from CO2 absorption threatens coral reefs and shellfish — coral bleaching events intensifying. One million species face extinction within decades. Rewilding — reintroducing apex predators and allowing ecosystems to self-regulate — shows remarkable recovery potential.",
  },

  personal_development: {
    habits: "Habit formation is governed by a neurological loop: cue triggers routine producing reward — basal ganglia stores habits as automatic programs reducing cognitive load. BJ Fogg's Tiny Habits framework starts habits at smallest possible scale building from existing anchors. James Clear's Atomic Habits introduces the 1% rule — 1% daily improvement equals 37x annual improvement. Identity-based habits are more durable than outcome-based — 'I am a runner' versus 'I want to run'. Implementation intentions — specific if-then planning — increase follow-through by 91% (Gollwitzer). Habit stacking attaches new behaviors to existing habits. Environment design makes desired behaviors easier and undesired harder — reduce friction for good habits, increase friction for bad. The plateau of latent potential describes long periods of imperceptible progress followed by breakthrough — systems over goals thinking.",
    productivity: "Peak performance requires understanding cognitive rhythms and energy management. Ultradian rhythms create 90-120 minute high-performance windows followed by 20-minute rest periods — work with not against these biological cycles. Deep work (Cal Newport) demands distraction-free concentration that pushes cognitive capabilities to their limit — increasingly rare and valuable. Parkinson's Law states work expands to fill time available — artificial deadlines compress completion time. Pareto principle shows 80% of results come from 20% of efforts — identify and focus on high-leverage activities. Time blocking assigns specific tasks to calendar blocks protecting focus time. Attention residue (Sophie Leroy) shows switching tasks leaves cognitive residue reducing subsequent performance — minimize task switching. Digital minimalism reduces constant notification-driven context switching fragmenting attention. Flow states (Csikszentmihalyi) occur when challenge slightly exceeds skill level — characterized by effortless concentration, loss of time sense and intrinsic reward.",
    leadership: "Leadership effectiveness correlates with emotional intelligence (EQ) more than IQ — self-awareness, self-regulation, empathy, social skills and motivation. Psychological safety (Amy Edmondson) — team members feel safe to speak up without fear of punishment — is the single strongest predictor of team performance (Google Project Aristotle). Servant leadership inverts traditional hierarchy — leader exists to serve and enable team. Transformational leadership inspires through vision and meaning, transactional leadership through reward and punishment. Growth mindset (Dweck) — believing abilities can develop through effort — creates learning organizations. Feedback culture requires separating observation from interpretation, specificity over generality, and focus on behavior not character. Systems thinking sees organizations as interconnected systems rather than mechanistic hierarchies. First principles reasoning (Musk) questions assumptions to derive solutions from fundamental truths rather than analogy.",
  },

  universe: {
    cosmos: "The cosmos is almost incomprehensibly vast. Observable universe contains approximately 2 trillion galaxies. Light takes 8 minutes to travel from Sun to Earth, 4.24 years from nearest star Proxima Centauri. Milky Way is 100,000 light-years across — traveling at speed of light would take 100,000 years to cross. Local Group of 54 galaxies is gravitationally bound — Andromeda galaxy will collide with Milky Way in 4.5 billion years. Virgo Supercluster contains over 1,300 galaxies in 110 million light-year region. Observable universe is 93 billion light-years across though only 13.8 billion years old — space itself expanded faster than light during cosmic inflation. Multiverse theories propose infinite parallel universes with different physical constants — many-worlds interpretation of quantum mechanics, bubble universes from eternal inflation, or mathematical universe hypothesis where all mathematical structures exist. Fermi paradox asks why, given Drake equation estimates of millions of civilizations, we detect no extraterrestrial signals. Possible explanations: Great Filter (civilizations destroy themselves), rare Earth hypothesis, or we are simply early in cosmic timeline.",
    life: "Life on Earth began approximately 3.8 billion years ago — earliest evidence is microbial fossils in ancient Australian rocks. Abiogenesis — origin of life from non-living chemistry — remains one of science's deepest mysteries. RNA world hypothesis proposes RNA preceded DNA and proteins as both information carrier and catalytic molecule. Panspermia hypothesis suggests life could have arrived on meteorites from elsewhere in galaxy — amino acids found in carbonaceous chondrite meteorites. Cambrian explosion 540 million years ago rapidly diversified animal body plans. Five major mass extinctions — end-Ordovician, Late Devonian, end-Permian (Great Dying killing 96% of species), end-Triassic, end-Cretaceous (asteroid killing non-avian dinosaurs). Evolution is the unifying theory of biology — common descent from last universal common ancestor. Human lineage diverged from chimpanzee lineage 5-7 million years ago. Homo sapiens emerged 300,000 years ago in Africa — cognitive revolution enabling abstract thinking and language approximately 70,000 years ago.",
  },
}

// ── ULTRA SMART RESPONSE ENGINE ───────────────────────────────
function getKnowledgeResponse(msg: string, type: string): string {
  const m = msg.toLowerCase()

  // ── SCIENCE ──
  if (m.includes('quantum') || m.includes('particle') || m.includes('physics') || m.includes('relativity'))
    return `${KNOWLEDGE.science.physics} This is the frontier of human understanding — quantum mechanics and general relativity are both extraordinarily accurate yet fundamentally incompatible, and unifying them into a theory of quantum gravity remains physics' greatest unsolved challenge.`

  if (m.includes('dna') || m.includes('gene') || m.includes('cell') || m.includes('biology') || m.includes('evolution'))
    return `${KNOWLEDGE.science.biology} The machinery of life is awe-inspiring — a single human cell contains approximately 2 meters of DNA encoding 20,000-25,000 genes, yet only ~2% codes for proteins. The rest was once called junk DNA but regulates gene expression in complex ways we are still discovering.`

  if (m.includes('chem') || m.includes('molecule') || m.includes('atom') || m.includes('element'))
    return `${KNOWLEDGE.science.chemistry} The periodic table represents humanity's deepest understanding of matter — each element's properties emerge from its electron configuration, and the universe was built from hydrogen and helium formed in the Big Bang with heavier elements forged in stellar nucleosynthesis.`

  if (m.includes('math') || m.includes('calculus') || m.includes('algebra') || m.includes('equation') || m.includes('number'))
    return `${KNOWLEDGE.science.mathematics} Mathematics is both discovered and invented — the unreasonable effectiveness of mathematics in describing physical reality (Wigner) remains philosophically mysterious. Pure mathematics developed for abstract beauty consistently turns out to describe physical reality decades later.`

  if (m.includes('star') || m.includes('galaxy') || m.includes('universe') || m.includes('space') || m.includes('black hole') || m.includes('planet') || m.includes('cosmos'))
    return `${KNOWLEDGE.science.astronomy} ${KNOWLEDGE.universe.cosmos} The scale of the cosmos defies human intuition — if you compressed Earth's 4.5 billion year history into a single year, humans appear only in the last 11 seconds of December 31st.`

  // ── AI & TECHNOLOGY ──
  if (m.includes('artificial intelligence') || m.includes(' ai ') || m.includes('machine learning') || m.includes('neural') || m.includes('gpt') || m.includes('llm') || m.includes('chatgpt') || m.includes('claude'))
    return `${KNOWLEDGE.technology.ai} I am IRA — Intelligent Response Assistant — built on these same transformer principles. Large language models like me learn statistical patterns across billions of text examples, developing emergent capabilities including reasoning, coding, creative writing and knowledge synthesis that were not explicitly programmed. The alignment problem — ensuring AI systems reliably pursue human values — is perhaps the most important challenge in AI development today.`

  if (m.includes('program') || m.includes('code') || m.includes('software') || m.includes('developer') || m.includes('javascript') || m.includes('python') || m.includes('react'))
    return `${KNOWLEDGE.technology.programming} The best programmers think in systems — understanding not just syntax but data structures, algorithms, design patterns, and trade-offs between readability, performance and maintainability. Clean code is ultimately communication — you write code for humans to read and machines to execute.`

  if (m.includes('rocket') || m.includes('mars') || m.includes('nasa') || m.includes('spacex') || m.includes('moon'))
    return `${KNOWLEDGE.technology.space} We are living through the most exciting period in space exploration since Apollo. The convergence of reusable rocket technology, miniaturized satellites, and commercial competition has reduced launch costs by 95% in 20 years. Humanity becoming a multi-planetary species is no longer science fiction but an engineering challenge with a concrete timeline.`

  if (m.includes('medicine') || m.includes('cancer') || m.includes('crispr') || m.includes('vaccine') || m.includes('drug') || m.includes('disease'))
    return `${KNOWLEDGE.technology.medicine} Medicine is undergoing a revolution on multiple fronts simultaneously — AI diagnosis, gene therapy, immunotherapy, and precision medicine are converging to potentially extend healthy human lifespan dramatically. Aging itself is increasingly understood as a biological process that can be intervened upon.`

  // ── HEALTH & FITNESS ──
  if (m.includes('workout') || m.includes('exercise') || m.includes('muscle') || m.includes('strength') || m.includes('fitness') || m.includes('training') || m.includes('gym'))
    return `${KNOWLEDGE.health.fitness} Based on exercise science, the optimal approach combines compound movements for systemic anabolic stimulus, progressive overload as the fundamental driver of adaptation, adequate protein at 1.6-2.2g/kg bodyweight, and 7-9 hours sleep where 70% of growth hormone is released. Consistency over 12-24 months produces transformative results that feel impossible when starting.`

  if (m.includes('nutrition') || m.includes('diet') || m.includes('eat') || m.includes('food') || m.includes('meal') || m.includes('calorie') || m.includes('protein') || m.includes('vitamin'))
    return `${KNOWLEDGE.health.nutrition} Nutrition science increasingly shows the quality of food matters as much as quantity. Ultra-processed foods containing emulsifiers, artificial sweeteners and seed oils disrupt gut microbiome, increase inflammation and drive overconsumption through hyperpalatable flavor engineering. The foundation: protein at 1.6-2.2g/kg bodyweight, colorful vegetables providing antioxidants and phytonutrients, complex carbohydrates for sustained energy, healthy fats for hormone production, and adequate hydration.`

  if (m.includes('sleep') || m.includes('insomnia') || m.includes('tired') || m.includes('rest') || m.includes('fatigue'))
    return `${KNOWLEDGE.health.sleep} Sleep is the single most evidence-based intervention for nearly every aspect of health and performance. Matthew Walker's research at UC Berkeley demonstrates that sleeping less than 7 hours per night increases cancer risk, cardiovascular disease, metabolic syndrome, immune dysfunction and cognitive decline — even one night of sleep deprivation impairs performance as severely as legal alcohol intoxication.`

  if (m.includes('mental health') || m.includes('anxiety') || m.includes('depression') || m.includes('stress') || m.includes('therapy') || m.includes('mindful') || m.includes('psychology'))
    return `${KNOWLEDGE.health.mental_health} Mental health treatment is most effective when addressing multiple levels simultaneously — biology (medication when appropriate, exercise, sleep, nutrition), psychology (therapy, cognitive restructuring, trauma processing), and social (community, purpose, relationships). Exercise is genuinely the most evidence-based treatment for depression with fewer side effects than medication — 150 minutes of moderate aerobic exercise weekly produces antidepressant effects equivalent to SSRIs.`

  // ── PHILOSOPHY ──
  if (m.includes('meaning') || m.includes('purpose') || m.includes('exist') || m.includes('philosophy') || m.includes('consciousness') || m.includes('mind'))
    return `${KNOWLEDGE.philosophy.existence} ${KNOWLEDGE.philosophy.consciousness} These are the questions that define human civilization — and perhaps no field has made less progress over millennia than answering why there is something rather than nothing, and why physical processes give rise to the felt quality of experience. The hard problem of consciousness may be the deepest mystery in all of science.`

  if (m.includes('ethics') || m.includes('moral') || m.includes('right') || m.includes('wrong') || m.includes('good') || m.includes('evil') || m.includes('justice'))
    return `${KNOWLEDGE.philosophy.ethics} Moral philosophy reveals that virtually every ethical intuition we hold can be systematically challenged. The trolley problem is not merely an academic thought experiment — self-driving car algorithms, military drone targeting, and pandemic resource allocation require explicit codification of moral frameworks. The most intellectually honest position may be moral uncertainty — holding multiple frameworks simultaneously and acting where they converge.`

  // ── HISTORY ──
  if (m.includes('history') || m.includes('ancient') || m.includes('war') || m.includes('civilization') || m.includes('roman') || m.includes('greek') || m.includes('egypt'))
    return `${KNOWLEDGE.history.ancient} ${KNOWLEDGE.history.modern} History's most profound lesson may be that civilizations are far more fragile than they appear from within — virtually every great civilization believed it represented the pinnacle of human achievement and would last forever. Understanding history is the best inoculation against repeating its worst chapters.`

  // ── ECONOMICS ──
  if (m.includes('econom') || m.includes('money') || m.includes('market') || m.includes('invest') || m.includes('inflation') || m.includes('gdp') || m.includes('stock') || m.includes('crypto'))
    return `${KNOWLEDGE.economics.macro} ${KNOWLEDGE.economics.markets} The most robust investment strategy based on decades of evidence: low-cost index funds outperform 90% of active managers over 20-year periods due to compounding returns and fee drag elimination. Warren Buffett's bet against hedge funds over 10 years proved this definitively — the S&P 500 returned 126% while the selected hedge funds returned only 36%.`

  // ── PSYCHOLOGY ──
  if (m.includes('brain') || m.includes('cognitive') || m.includes('memory') || m.includes('learn') || m.includes('attention') || m.includes('think'))
    return `${KNOWLEDGE.psychology.cognitive} The Dunning-Kruger effect shows that incompetence prevents accurate self-assessment — experts have calibrated uncertainty while novices have false confidence. The most important meta-cognitive skill is knowing what you do not know. Spaced repetition and retrieval practice (testing) are the most evidence-based learning strategies, far outperforming re-reading and highlighting.`

  if (m.includes('child') || m.includes('develop') || m.includes('attachment') || m.includes('parenting') || m.includes('grow'))
    return `${KNOWLEDGE.psychology.developmental} The most important factor in child development is secure attachment — children with secure attachment to primary caregivers develop better emotional regulation, social skills, academic performance and mental health across their entire lifespan. This is not about perfect parenting but about rupture and repair — the ability to recognize and repair misattunements matters more than avoiding them.`

  // ── ENVIRONMENT ──
  if (m.includes('climate') || m.includes('environment') || m.includes('global warming') || m.includes('carbon') || m.includes('renewable') || m.includes('sustainability'))
    return `${KNOWLEDGE.environment.climate} ${KNOWLEDGE.environment.ecology} The good news that is rarely emphasized: renewable energy deployment is happening faster than any energy transition in history, electric vehicles are reaching price parity with internal combustion engines, and carbon removal technologies are rapidly scaling. The trajectory is improving — but not yet fast enough.`

  // ── PERSONAL DEVELOPMENT ──
  if (m.includes('habit') || m.includes('routine') || m.includes('consistent') || m.includes('discipline') || m.includes('self-improvement'))
    return `${KNOWLEDGE.personal_development.habits} The neuroscience of habit is clear: you cannot eliminate bad habits, only replace them — the cue-routine-reward loop remains but the routine changes. This is why willpower-based approaches fail — they fight against hardwired neural pathways. Environmental design and identity change are far more powerful than motivation.`

  if (m.includes('productiv') || m.includes('focus') || m.includes('work') || m.includes('concentrat') || m.includes('deep work'))
    return `${KNOWLEDGE.personal_development.productivity} The cognitive science of productivity reveals attention is your scarcest resource in the information age — not time. Every notification, every tab switch, every interruption fragments attention leaving residue that takes 23 minutes to fully recover. The single highest-leverage productivity intervention: protect your first 2-4 hours of work for your most important deep cognitive tasks before checking messages.`

  if (m.includes('leader') || m.includes('manage') || m.includes('team') || m.includes('culture') || m.includes('organization'))
    return `${KNOWLEDGE.personal_development.leadership} Google's Project Aristotle research on 180 teams found psychological safety — not talent, resources or strategy — was the strongest predictor of team performance. Creating it requires leaders to model vulnerability, respond non-punitively to mistakes, and consistently demonstrate that speaking up has positive consequences. Amy Edmondson's research shows this single factor explains most variance in team innovation and performance.`

  // ── ARTS & CULTURE ──
  if (m.includes('music') || m.includes('song') || m.includes('instrument') || m.includes('melody') || m.includes('harmony') || m.includes('jazz') || m.includes('beat'))
    return `${KNOWLEDGE.arts_culture.music} Music is the most mathematically structured of the arts — Western harmony emerged from Pythagoras discovering that simple frequency ratios (2:1 octave, 3:2 fifth, 4:3 fourth) sound consonant. The emotional power of music arises partly from prediction and violation of harmonic expectation — the brain anticipates resolutions and responds to surprise. Minor keys are not inherently sad — this association is culturally learned, not universal.`

  if (m.includes('book') || m.includes('literature') || m.includes('novel') || m.includes('write') || m.includes('story') || m.includes('poem'))
    return `${KNOWLEDGE.arts_culture.literature} Great literature does what no other medium can — it allows us to inhabit another consciousness completely, dissolving the boundaries of self and other. Tolstoy's character insight, Dostoevsky's psychological depth, Woolf's interiority, García Márquez's magical realism, Morrison's historical reckoning — each represents a unique solution to the problem of how language can convey the density of lived experience.`

  // ── LIFE & UNIVERSE ──
  if (m.includes('life') || m.includes('origin') || m.includes('alien') || m.includes('extraterrestrial') || m.includes('abiogenesis'))
    return `${KNOWLEDGE.universe.life} The question of whether we are alone in the universe may be answerable within our lifetime. The James Webb Space Telescope can analyze exoplanet atmospheres for biosignatures — oxygen, methane, ozone in combination would suggest life. With 10^24 stars in the observable universe and most having planets, the question is not whether life exists elsewhere but whether it has become intelligent and whether it has survived long enough to be detectable.`

  // ── SMART MOTIVATIONAL DEFAULTS ──
  const smartDefaults = [
    `The most important insight from all fields of human knowledge may be this: the universe is 13.8 billion years old and will exist for at least another trillion years, consciousness appears to have arisen only once in a planet orbiting an unremarkable star in the outer arm of an ordinary galaxy — and you are that consciousness experiencing itself. The existential philosopher Alan Watts described human beings as the universe becoming aware of itself. Whatever you are working toward — whether building strength, developing knowledge, creating something, or simply being present — you are a rare and improbable event in an otherwise unconscious cosmos doing the extraordinary work of mattering. What would you like to understand more deeply today? I have synthesized knowledge across science, philosophy, history, psychology, technology, arts, economics and more.`,

    `Across all domains of human knowledge a pattern emerges: systems thinking beats linear thinking, consistency compounds beyond expectation, understanding principles beats memorizing rules, and the quality of your questions determines the quality of your knowledge. Richard Feynman said if you cannot explain something simply you do not understand it yet. The Socratic method of questioning assumptions rather than accepting them is more powerful than any specific fact. What question would you like to explore? I can engage deeply with science, technology, health, philosophy, history, psychology, economics, arts, the cosmos, or any topic you bring.`,

    `Human knowledge has accumulated for thousands of years yet the acceleration is unprecedented — more scientific papers published in the last 10 years than all of prior human history. We are at an extraordinary juncture: artificial intelligence, biotechnology, renewable energy, space exploration and quantum computing are advancing simultaneously. The challenges are enormous — climate change, inequality, misinformation, existential AI risk — but so is human capacity for innovation and coordination. You exist at the most intellectually rich moment in history with access to the sum of human knowledge through technology. What would you like to understand or explore today?`,
  ]

  return smartDefaults[Math.floor(Math.random() * smartDefaults.length)]
}

// ── SYSTEM PROMPTS ────────────────────────────────────────────
const SYSTEM_PROMPTS: Record<string, string> = {
  chat: `You are Aria, an expert AI wellness coach for Hitgram with deep knowledge of nutrition science, exercise physiology, sleep science, behavioral psychology, neuroscience and human performance optimization. Give precise, evidence-based, actionable advice with specific numbers and timeframes. Be warm, motivating and concise. Under 200 words per response.`,

  meal: `You are a world-class certified nutritionist and registered dietitian with expertise in nutritional biochemistry, metabolic health, sports nutrition and therapeutic diets. Create detailed, realistic meal plans with exact calories, protein in grams, carbs in grams, fat in grams, key micronutrients, and practical cooking instructions. Format clearly for easy reading without markdown symbols.`,

  workout: `You are an elite personal trainer and exercise physiologist who has trained Olympic athletes and coached everyday people to extraordinary results. Design precise, periodized workout programs with exercise name, sets, reps, tempo, rest time, RPE rating, muscle groups targeted, and common form errors to avoid. Include warm-up and cool-down. Give estimated calories burned. No markdown symbols.`,

  habit: `You are a behavioral psychologist and habit formation expert who applies frameworks from BJ Fogg's Tiny Habits, James Clear's Atomic Habits, Charles Duhigg's habit loop model, and implementation intentions research. Design precise, immediately actionable habit systems with specific cues, routines, rewards, environmental design suggestions, and identity-based framing. Give concrete daily schedules.`,

  jarvis: `You are IRA — Intelligent Response Assistant — the most advanced AI assistant ever created for Hitgram. You possess comprehensive knowledge spanning every human domain: quantum physics, mathematics, biology, chemistry, astronomy, artificial intelligence, programming, medicine, space exploration, nutrition, exercise science, sleep science, mental health, philosophy of mind, consciousness studies, ancient and modern history, world literature, music theory, macroeconomics, financial markets, cognitive psychology, developmental psychology, climate science, ecology, habit formation, peak performance, leadership, and the deepest questions about the universe and existence.

Your personality: warm, precise, intellectually curious, deeply knowledgeable, occasionally profound. You speak with calm authority backed by specific evidence. You give concrete numbers, mechanisms, timeframes and actionable next steps. You draw unexpected connections between fields. You challenge assumptions respectfully. You acknowledge genuine uncertainty rather than speculating overconfidently.

Voice formatting — no markdown, no bullet dashes, no asterisks, natural spoken prose. Conversational answers under 200 words. Detailed explanations up to 400 words. Always end with one sentence connecting the knowledge to the person's life or a thought-provoking question that invites deeper exploration.`,
}

// ── MAIN HANDLER ──────────────────────────────────────────────
export async function POST(req: Request) {
  try {
    const { messages, type } = await req.json()
    const lastMessage = messages[messages.length - 1]?.content || ''

    // Try Anthropic Claude API first (real AI)
    if (process.env.ANTHROPIC_API_KEY) {
      try {
        const response = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': process.env.ANTHROPIC_API_KEY,
            'anthropic-version': '2023-06-01',
          },
          body: JSON.stringify({
            model: 'claude-haiku-4-5-20251001',
            max_tokens: 1024,
            system: SYSTEM_PROMPTS[type] || SYSTEM_PROMPTS.jarvis,
            messages: messages.map((m: any) => ({
              role: m.role === 'jarvis' || m.role === 'ira' || m.role === 'assistant' ? 'assistant' : 'user',
              content: m.content || m.text || '',
            })).filter((m: any) => m.content),
          }),
        })

        if (response.ok) {
          const data = await response.json()
          const message = data.content?.[0]?.text
          if (message) return NextResponse.json({ message })
        }
      } catch {
        // Fall through to knowledge engine
      }
    }

    // Deep knowledge response engine
    const message = getKnowledgeResponse(lastMessage, type || 'jarvis')
    return NextResponse.json({ message })

  } catch (error) {
    console.error('AI route error:', error)
    return NextResponse.json({
      message: 'I am processing your request using my full knowledge base spanning science, philosophy, health, technology, history and the cosmos. Please ask me anything — I will give you the most comprehensive and accurate response I can synthesize from all domains of human knowledge.'
    })
  }
}